name: Build

on: workflow_dispatch 

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v7
      with:
        version: '2.0.12'
        actions-cache-folder: 'emsdk-cache'
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Fetch & Build
      run: |
        chmod +x ./build.sh
        ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ffmpeg
        path: |
          dist/
        if-no-files-found: ignore # 'warn' or 'ignore' are also available, defaults to `warn`
        retention-days: 1
